---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-create-an-image"
      label: "イメージの作成"
      solveButton: true
    - name: "02-deploy-an-image"
      label: "イメージのデプロイ"
      solveButton: true
    - name: "03-add-software-to-image"
      label: "ソフトウェアの追加"
      solveButton: true
    - name: "04-apply-image"
      label: "イメージの適用"
      solveButton: true

tabs:
  - name: "Build host"
    url: /wetty/ssh/root
  - name: "VM SSH session"
    url: /wetty_bootc_vm/ssh/root
