Red Hat Enterprise Linux のラボ体験へようこそ。

このテキストの横に表示されているビルドホストは、Subscription Manager に登録された Red Hat Enterprise Linux 10 システムです。

Image mode では、標準的なコンテナツールを使用して bootc イメージの定義、ビルド、転送を行います。このホストにはビルド環境として Podman がすでにインストールされており、いくつかの追加ファイルと必要なイメージも用意されています。


== Containerfile の確認

Image mode では、OS の内容を定義するために標準的な Containerfile を使用します。
[source,bash,run,subs=attributes+]
----
cat Containerfile
----


[source,dockerfile,nocopy]
----
FROM registry.redhat.io/rhel10/rhel-bootc:10.1 # <1>

ADD etc /etc # <2>

RUN dnf install -y httpd # <3>
RUN systemctl enable httpd
----
<1> `+FROM+` 行はベースイメージを定義します。ここでは一般的な UBI アプリケーションベースイメージではなく、新しい `+bootc+` ベースイメージを使用しています。
<2> `+ADD+` 行により、アプリケーションコンテナと同様にディレクトリの内容をまとめて追加できます。
<3> `+RUN+` ディレクティブにより、アプリケーションコンテナと同様にソフトウェアの追加やサービスの起動を行います。

アプリケーションコンテナとは異なり、`+ENTRYPOINT+` や `+CMD+` ディレクティブではなく、`+systemctl+` を使用してサービスを有効化しています。これらのイメージはホストとして動作するため、コンテナエンジンがプロセス起動に使用するこれらの設定ディレクティブは適用されません。起動後は `+systemd+` が PID1 として動作します。

== 追加される設定の確認

ホストの `+/etc+` にシステム設定を反映するためのファイル一式があります。その中の1つを見てみましょう。

[source,bash,run,subs=attributes+]
----
cat etc/sudoers.d/wheel
----

ドロップインファイルを使用して、`+wheel+` グループに NOPASSWD ルールを適用しています。これはイメージビルド内でポリシーを設定する方法の一例です。

[source,nocopy]
----
%wheel  ALL=(ALL)   NOPASSWD: ALL
----

== コンテナのビルドとレジストリへのプッシュ

Image mode では、他のアプリケーションコンテナと同様に、OCI 標準のコンテナツールを使用して bootc イメージをビルドします。`+podman build+` でこのイメージをビルドしてみましょう。

[source,bash,run,subs=attributes+]
----
podman build -t builder-{guid}.{domain}/test-bootc .
----

ビルドが完了すると、bootc イメージは OCI 標準のコンテナレジストリを使用して配布されます。このラボでは単純なレジストリを使用していますが、エンタープライズレジストリではコンテンツの検査、履歴の確認、タグの管理などの機能が提供されます。

[source,bash,run,subs=attributes+]
----
podman push builder-{guid}.{domain}/test-bootc
----

シンプルな Web サーバーに必要なのはこれだけです！他の RHEL ホストと同様に、一般的な管理ソフトウェアやアプリケーションソフトウェアをイメージに追加できます。次の演習では、ビルドからデプロイへの流れを見ていきましょう。
